# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 1036)
        MainWindow.setMaximumSize(QtCore.QSize(813, 1036))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget.setStyleSheet("align-items:center;\n"
"justify-content:center;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setEnabled(True)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_73 = QtWidgets.QLabel(self.frame_4)
        self.label_73.setMinimumSize(QtCore.QSize(0, 120))
        self.label_73.setStyleSheet("\n"
"color:red;\n"
"")
        self.label_73.setObjectName("label_73")
        self.verticalLayout_9.addWidget(self.label_73, 0, QtCore.Qt.AlignTop)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_9.setContentsMargins(50, 20, 50, 20)
        self.formLayout_9.setHorizontalSpacing(15)
        self.formLayout_9.setVerticalSpacing(25)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_74 = QtWidgets.QLabel(self.frame_4)
        self.label_74.setMinimumSize(QtCore.QSize(150, 0))
        self.label_74.setObjectName("label_74")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_74)
        self.label_75 = QtWidgets.QLabel(self.frame_4)
        self.label_75.setMinimumSize(QtCore.QSize(150, 0))
        self.label_75.setObjectName("label_75")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_75)
        self.textEdit_58 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_58.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_58.setObjectName("textEdit_58")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_58)
        self.label_76 = QtWidgets.QLabel(self.frame_4)
        self.label_76.setMinimumSize(QtCore.QSize(150, 0))
        self.label_76.setObjectName("label_76")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_76)
        self.textEdit_59 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_59.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_59.setObjectName("textEdit_59")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit_59)
        self.label_77 = QtWidgets.QLabel(self.frame_4)
        self.label_77.setMinimumSize(QtCore.QSize(150, 0))
        self.label_77.setObjectName("label_77")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_77)
        self.textEdit_60 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_60.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_60.setObjectName("textEdit_60")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textEdit_60)
        self.label_78 = QtWidgets.QLabel(self.frame_4)
        self.label_78.setMinimumSize(QtCore.QSize(150, 0))
        self.label_78.setObjectName("label_78")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_78)
        self.textEdit_61 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_61.setMaximumSize(QtCore.QSize(16777215, 60))
        self.textEdit_61.setObjectName("textEdit_61")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textEdit_61)
        self.label_79 = QtWidgets.QLabel(self.frame_4)
        self.label_79.setMinimumSize(QtCore.QSize(150, 0))
        self.label_79.setObjectName("label_79")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_79)
        self.textEdit_62 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_62.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_62.setObjectName("textEdit_62")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textEdit_62)
        self.label_80 = QtWidgets.QLabel(self.frame_4)
        self.label_80.setMinimumSize(QtCore.QSize(150, 0))
        self.label_80.setObjectName("label_80")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_80)
        self.textEdit_63 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_63.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_63.setObjectName("textEdit_63")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.textEdit_63)
        self.label_81 = QtWidgets.QLabel(self.frame_4)
        self.label_81.setMinimumSize(QtCore.QSize(150, 0))
        self.label_81.setObjectName("label_81")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_81)
        self.frame_16 = QtWidgets.QFrame(self.frame_4)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.radioButton_25 = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_25.setGeometry(QtCore.QRect(20, 10, 95, 20))
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_26 = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_26.setGeometry(QtCore.QRect(200, 10, 95, 20))
        self.radioButton_26.setObjectName("radioButton_26")
        self.radioButton_27 = QtWidgets.QRadioButton(self.frame_16)
        self.radioButton_27.setGeometry(QtCore.QRect(380, 10, 95, 20))
        self.radioButton_27.setObjectName("radioButton_27")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.frame_16)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_9.setObjectName("checkBox_9")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkBox_9)
        self.frame_13 = QtWidgets.QFrame(self.frame_4)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_17.setStyleSheet("background-color:red;\n"
"color:white;\n"
"font-size:25px;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_10.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_18.setStyleSheet("color:red;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_10.addWidget(self.pushButton_18)
        self.formLayout_9.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.frame_13)
        self.textEdit_57 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_57.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_57.setObjectName("textEdit_57")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_57)
        self.verticalLayout_9.addLayout(self.formLayout_9)
        self.gridLayout_6.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_73.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">SIGNUP</span></p></body></html>"))
        self.label_74.setText(_translate("MainWindow", "Username"))
        self.label_75.setText(_translate("MainWindow", "First Name"))
        self.label_76.setText(_translate("MainWindow", "Last Name"))
        self.label_77.setText(_translate("MainWindow", "Email Id"))
        self.label_78.setText(_translate("MainWindow", "Address"))
        self.label_79.setText(_translate("MainWindow", "Password"))
        self.label_80.setText(_translate("MainWindow", "Confirm Password"))
        self.label_81.setText(_translate("MainWindow", "Gender"))
        self.radioButton_25.setText(_translate("MainWindow", "Male"))
        self.radioButton_26.setText(_translate("MainWindow", "Female"))
        self.radioButton_27.setText(_translate("MainWindow", "Other"))
        self.checkBox_9.setText(_translate("MainWindow", "By Clicking on this checkbox you agree to the terms and condition of fitness buddy"))
        self.pushButton_17.setText(_translate("MainWindow", "Sign-up"))
        self.pushButton_18.setText(_translate("MainWindow", "Go Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

